apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: detection1
  namespace: serverless
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/window: 60s
    spec:
      containers:
        - name: application1
          image: trourest186/multiple_mix
          resources:
            requests:
              cpu: "1000m"
          ports:
            - containerPort: 8881
      nodeSelector:
        kubernetes.io/hostname: mec
