apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: detection1
  namespace: serverless
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/window: 6s
    spec:
      containers:
      - image: trourest186/multiple_process@sha256:70c4a7d9fd23a17e3e261f1c7ab727ee061db9547692e8bc4e6349fc10c6ac2e
        resources:
          limits:
            cpu: "1000m"
        ports:
        - containerPort: 8080
      nodeSelector:
        kubernetes.io/hostname: mec