apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: detection1
  namespace: serverless
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/window: 2000s
    spec:
      containers:
      - name: application1
        image: trourest186/pts:testbed
        command:
        - /bin/bash
        - -c
        args:
        - |
          if [ ! -f /tmp/command_complete ]; then
            FORCE_TIMES_TO_RUN=10 MONITOR=cpu.power,cpu.temp,cpu.usage TEST_RESULTS_NAME=TESTTEST ./phoronix-test-suite/phoronix-test-suite batch-run encode-flac-1.7.0; sshpass -p 'kienlu123' scp -r /var/lib/phoronix-test-suite/test-results/ kien@172.16.42.11:~/storage/
            touch /tmp/command_complete
          fi
        resources:
          limits:
            cpu: 1000m
        ports:
        - containerPort: 8881
      nodeSelector:
        kubernetes.io/hostname: mec
